name: Auto Update Flox

on:
  workflow_dispatch:
  
jobs:
  check_for_updates:
    name: Check for Flox updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Make Request
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://pypi.python.org/pypi/flox-lib/json"
          method: GET
      - name: Show Response
        run: |
          echo ${{ fromJson(steps.myRequest.outputs.response).info.version }}
      - name: Read package.json
        id: reqs
        uses: juliangruber/read-file-action@v1
        with:
          path: ./requirements.txt
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ steps.reqs.outputs.content }}
          regex: '^flox-lib[\=\>\<\!]{2}\d+\.\d+\.\d+$'
      - name: Find and Replace
        if: ${{ steps.regex-match.outputs.match }} != ${{ steps.reqs.outputs.content }}
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: ${{ steps.reqs.outputs.content }}
          replace: ${{ fromJson(steps.myRequest.outputs.response).info.version }}
          regex: false

