name: Auto Update Flox

on:
  workflow_dispatch:
  
jobs:
  check_for_updates:
    name: Check for Flox updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Make Request
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://pypi.python.org/pypi/flox-lib/json"
          method: GET
      - name: Show Response
        run: |
          echo ${{ fromJson(steps.myRequest.outputs.response).info.version }}
