name: "Update"
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags-ignore:
      - 'v*'
    paths-ignore: 
      - .github/workflows/*
      - README.md
      - assets/*
env:
  PYTHON_VER: 3.8
jobs:
  update-version:
    uses: ./.github/workflows/update-version.yml
  deps:
    needs: update-version
    if: ${{ github.ref == 'refs/heads/main' }}
    name: "Build"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ env.PYTHON_VER }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VER }}
      - uses: actions/cache@v2
        if: startsWith(runner.os, 'Windows')
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r ./requirements.txt -t ./lib
      - name: Get Plugin's version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'plugin.json'
          prop_path: 'Version'
      - name: Get main version
        id: main_version
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://raw.githubusercontent.com/${{github.repository}}/main/plugin.json"
          method: 'GET'
      - name: Bump release version
        if: ${{ fromJson(steps.main_version.outputs.response).Version }} != ${{ steps.version.outputs.prop }}
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.version.outputs.prop }}
          version-fragment: 'bug'
      - name: Update my-file.json description
        if: ${{ fromJson(steps.main_version.outputs.response).Version }} != ${{ steps.version.outputs.prop }}
        uses: jossef/action-set-json-field@v2
        with:
          file: plugin.json
          field: Version
          value: ${{ fromJson(steps.main_version.outputs.response).Version }} ${{ steps.bump_version.outputs.next-version }}
      - name: Get Plugin's version
        id: final_version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'plugin.json'
          prop_path: 'Version'
      - name: Package files
        run: |
          git clone https://github.com/Garulf/flow_commands/ bin
          pip install -r ./bin/requirements.txt
          python ./bin/commands.py package -n "${{github.event.repository.name}}.zip"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: "./${{github.event.repository.name}}.zip"
          tag_name: "v${{steps.final_version.outputs.prop}}"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
