name: "Update Version"
on:
  workflow_dispatch:
  
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Get Plugin's version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'plugin.json'
          prop_path: 'Version'
      - name: Bump release version
        if: ${{ steps.previoustag.outputs.tag }} == ${{ steps.version.outputs.prop }}
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.version.outputs.prop }}
          version-fragment: 'bug'
      - name: Update plugin.json description
        if: ${{ steps.previoustag.outputs.tag }} == ${{ steps.version.outputs.prop }}
        uses: jossef/action-set-json-field@v2
        with:
          file: plugin.json
          field: Version
          value: ${{ steps.bump_version.outputs.next-version }}
      - name: commit & push
        if: ${{ steps.previoustag.outputs.tag }} == ${{ steps.version.outputs.prop }}
        run: |
          git config --local user.email github-actions[bot]@users.noreply.github.com
          git config --local user.name github-actions[bot]
          git add plugin.json
          git commit -m "Bump version to ${{ steps.bump_version.outputs.next-version }}"
          git push
